### ISSUE TITLE
Basic Authentication

### ISSUE THREAD

**Issue by senolatac** [wilchn/BlazingQuartz#37]
Is it possible to access the web-ui with basic auth via docker?

**Comment by senolatac** [comment]
Solved with, nginx-auth:

```
version: "3.8"

services:
  quartz-ui:
    image: wilchn/blazingquartzapp:0.7.0
    container_name: BlazingQuartzApp
    hostname: BlazingQuartzApp
    volumes:
      - ./blazingquartz_path/BlazingQuartzDb.db:/app/BlazingQuartzDb.db
      - ./blazingquartz_path/logs:/app/logs
      - ./blazingquartz_path/certs:/app/certs
      - ./blazingquartz_path/appsettings.json:/app/appsettings.json
    environment:
      TZ: 'Asia/Istanbul'
      ASPNETCORE_HTTP_PORTS: 8080

  nginxcomauth:
    image: beevelop/nginx-basic-auth:v2023.10.1
    ports:
      - '8686:80'
    depends_on:
      - quartz-ui
    environment:
      - HTPASSWD=...
      - FORWARD_PORT=8080
      - FORWARD_HOST=quartz-ui
```
